#!/usr/bin/env python3
"""Emit the embedded @font-face block for theme.css.

Obsidian injects theme.css into a <style> tag, so relative url() paths do NOT
resolve against the theme folder — local font files can't be referenced by
path. The only way to ship fonts inside a theme is to embed them as base64
data URIs. This script generates that block from the .woff2 files in this
folder (latin + latin-ext subsets, matching the unicode-range split Google
Fonts uses).

Usage (from the theme folder):
    python3 fonts/embed.py > /tmp/fonts.css
then paste the output over the "EMBEDDED FONTS" section at the end of theme.css.
"""
import base64
from pathlib import Path

HERE = Path(__file__).parent

LATIN = ("U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, "
         "U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, "
         "U+2212, U+2215, U+FEFF, U+FFFD")
LATIN_EXT = ("U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, "
             "U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, "
             "U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF")

# (family, style, weight, latin file, latin-ext file)
FACES = [
    ("Fira Sans",      "normal", "400",     "FiraSans-400.woff2",         "FiraSans-400-ext.woff2"),
    ("Fira Sans",      "normal", "500",     "FiraSans-500.woff2",         "FiraSans-500-ext.woff2"),
    ("Fira Sans",      "normal", "600",     "FiraSans-600.woff2",         "FiraSans-600-ext.woff2"),
    ("Fira Sans",      "normal", "700",     "FiraSans-700.woff2",         "FiraSans-700-ext.woff2"),
    ("JetBrains Mono", "normal", "400 700", "JetBrainsMono.woff2",        "JetBrainsMono-ext.woff2"),
    ("JetBrains Mono", "italic", "400 700", "JetBrainsMono-Italic.woff2", "JetBrainsMono-Italic-ext.woff2"),
]


def face(family, style, weight, filename, unicode_range):
    data = base64.b64encode((HERE / filename).read_bytes()).decode("ascii")
    return (
        "@font-face {\n"
        f"  font-family: '{family}'; font-style: {style}; font-weight: {weight}; font-display: swap;\n"
        f"  unicode-range: {unicode_range};\n"
        f"  src: url(data:font/woff2;base64,{data}) format('woff2');\n"
        "}\n"
    )


out = [
    "/* ------------------------------------------------------------------\n"
    "   EMBEDDED FONTS  (GENERATED by fonts/embed.py — do not hand-edit)\n"
    "   ------------------------------------------------------------------\n"
    "   Obsidian injects theme.css as a <style> tag, so url('fonts/…') would\n"
    "   resolve against app://obsidian.md and never find the files. The faces\n"
    "   below are therefore embedded as base64. Sources live in ./fonts.\n"
    "   ------------------------------------------------------------------ */\n"
]
for family, style, weight, latin_file, ext_file in FACES:
    out.append(face(family, style, weight, latin_file, LATIN))
    out.append(face(family, style, weight, ext_file, LATIN_EXT))

# The marker companion face (built by make-marks.py): empty glyphs for the
# characters of a Live Preview block marker. Its unicode-range is exactly
# those code points, so it never touches anything else.
out.append(face("Klartext Marks", "normal", "400", "KlartextMarks.woff2",
                "U+0020, U+0029-002B, U+002D-002E, U+003E"))

print("".join(out), end="")
